### ISSUE TITLE
Remove auth-key from repo

### ISSUE THREAD

**Issue by CorruptComputer** [elian1203/UrbanMarket#1]
https://github.com/elian1203/UrbanMarket/blob/1e719121f1920fabdd52d2cb5b4f6e4f2af3ab32/src/config.yml#L3

This is a bad idea and gives anyone who see's it access. Although you don't have the public IP its still not a good thing to do.

**Comment by elian1203** [comment]
That's just a spammage of keys, the real key is much longer.
